name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: update packages
      run: sudo apt update
    # - name: upgrade packages
      # run: sudo apt -y upgrade
    - name: install packages
      run: sudo apt install -y g++ make cmake catch2 libopencv-dev
    - uses: actions/checkout@v4

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -S . -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ./build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ./build/ --output-on-failure -C ${{env.BUILD_TYPE}}

